name: Frontend Test

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type-check || true

      - name: Lint check
        run: npm run lint || true

      - name: Run tests
        run: npm test
        env:
          CI: true
          VITE_API_URL: ${{ secrets.API_URL }}

      - name: Build check
        run: npm run build
        env:
          VITE_API_URL: ${{ secrets.API_URL }} 